url: "https://secure.gravatar.com/avatar/"
gravatarLink: "http://gravatar.com/emails"
min_length_password: 6
max_length_email: 225
content_length: 140
micropost_items: 10
max_length_name: 50
min_length_email: 4
standard_memory: 5
min_length_name: 3
feed_items: 5
check_box: 1
size: 60
x: 400
y: 400
show_limit:
  show_5: 5
  show_10: 10
  show_15: 15
  show_20: 20
  show_30: 30
  show_50: 50
