size: 80
url: "https://secure.gravatar.com/avatar/"
min_length_name: 3
min_length_email: 4
max_length_name: 50
max_length_email: 225
min_length_password: 6
check_box: 1
gravatarLink: "http://gravatar.com/emails"
show_limit:
  show_5: 5
  show_10: 10
  show_15: 15
  show_20: 20
  show_30: 30
  show_50: 50
